name: Publish latest to docker

on:
  push:
    branches:
      - master

jobs:

  release:
    strategy:
      matrix:
        node_version: [12.x]
        os: [ubuntu-latest]

    if: github.repository == 'PasteUs/PasteMeFrontend'
    name: Build with node ${{ matrix.node_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: build and update cdn
        run: |
          GH_TOKEN=${{ secrets.GITHUB_PASSWORD }} bash .github/shell/build_and_update_cdn.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Aliyun DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
            linux/386
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-frontend:beta

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: trigger webhook
        run: |
          curl -X POST ${{ secrets.MASTER_WEBHOOK }}
