name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  draft_release:
    if: github.repository == 'PasteUs/PasteMeFrontend'
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Draft
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
